### ISSUE TITLE
Date of birth required by nwb_builder

### ISSUE THREAD

**Issue by rsnevers** [LorenFrankLab/rec_to_nwb#53]
The `date_of_birth` key-value pair in the metadata isn't required in the [metadata extractor](https://github.com/LorenFrankLab/rec_to_nwb/blob/8b1c219e5ad89fbc6b1719a040c59405e153a654/rec_to_nwb/processing/metadata/metadata_extractor.py#L12-L18) but is in the [nwb builder](https://github.com/LorenFrankLab/rec_to_nwb/blob/8b1c219e5ad89fbc6b1719a040c59405e153a654/rec_to_nwb/processing/builder/nwb_file_builder.py#L398-L413). Conversion from .rec files to .nwb files fail at this step if .yml subject metadata doesn't contain a `date_of_birth` key-value pair.

**Comment by edeno** [comment]
I can raise an error there so it is more informative.
